export default {
    POPULAR_MOVIES: 'POPULAR_MOVIES',
    TOP_RATED_MOVIES: 'TOP_RATED_MOVIES',
    UPCOMING_MOVIES: 'UPCOMING_MOVIES',
    NOW_PLAYING_MOVIES: 'NOW_PLAYING_MOVIES',
    LATEST_MOVIES: 'LATEST_MOVIES',
}