
export default {
  COUNTRY_CODE: [
    { text: "Andorra", country_id: "AD", country_icon: "" },
    { text: "United Arab Emirates", country_id: "AE", country_icon: "" },
    { text: "Afghanistan", country_id: "AF", country_icon: "" },
    { text: "Antigua and Barbuda", country_id: "AG", country_icon: "" },
    { text: "Anguilla", country_id: "AI", country_icon: "" },
    { text: "Albania", country_id: "AL", country_icon: "" },
    { text: "Armenia", country_id: "AM", country_icon: "" },
    { text: "Netherlands Antilles", country_id: "AN", country_icon: "" },
    { text: "Angola", country_id: "AO", country_icon: "" },
    { text: "Antarctica", country_id: "AQ", country_icon: "" },
    { text: "Argentina", country_id: "AR", country_icon: "" },
    { text: "American Samoa", country_id: "AS", country_icon: "" },
    { text: "Austria", country_id: "AT", country_icon: "" },
    { text: "Australia", country_id: "AU", country_icon: "" },
    { text: "Aruba", country_id: "AW", country_icon: "" },
    { text: "Azerbaijan", country_id: "AZ", country_icon: "" },
    { text: "Bosnia and Herzegovina", country_id: "BA", country_icon: "" },
    { text: "Barbados", country_id: "BB", country_icon: "" },
    { text: "Bangladesh", country_id: "BD", country_icon: "" },
    { text: "Belgium", country_id: "BE", country_icon: "" },
    { text: "Burkina Faso", country_id: "BF", country_icon: "" },
    { text: "Bulgaria", country_id: "BG", country_icon: "" },
    { text: "Bahrain", country_id: "BH", country_icon: "" },
    { text: "Burundi", country_id: "BI", country_icon: "" },
    { text: "Benin", country_id: "BJ", country_icon: "" },
    { text: "Bermuda", country_id: "BM", country_icon: "" },
    { text: "Brunei Darussalam", country_id: "BN", country_icon: "" },
    { text: "Bolivia", country_id: "BO", country_icon: "" },
    { text: "Brazil", country_id: "BR", country_icon: "" },
    { text: "Bahamas", country_id: "BS", country_icon: "" },
    { text: "Bhutan", country_id: "BT", country_icon: "" },
    { text: "Bouvet Island", country_id: "BV", country_icon: "" },
    { text: "Botswana", country_id: "BW", country_icon: "" },
    { text: "Belize", country_id: "BZ", country_icon: "" },
    { text: "Belarus", country_id: "BY", country_icon: "" },
    { text: "Canada", country_id: "CA", country_icon: "" },
    { text: "Cocos  Islands", country_id: "CC", country_icon: "" },
    { text: "Congo", country_id: "CD", country_icon: "" },
    { text: "Central African Republic", country_id: "CF", country_icon: "" },
    { text: "Congo", country_id: "CG", country_icon: "" },
    { text: "Switzerland", country_id: "CH", country_icon: "" },
    { text: "Cote D'Ivoire", country_id: "CI", country_icon: "" },
    { text: "Cook Islands", country_id: "CK", country_icon: "" },
    { text: "Chile", country_id: "CL", country_icon: "" },
    { text: "Cameroon", country_id: "CM", country_icon: "" },
    { text: "China", country_id: "CN", country_icon: "" },
    { text: "Colombia", country_id: "CO", country_icon: "" },
    { text: "Costa Rica", country_id: "CR", country_icon: "" },
    { text: "Serbia and Montenegro", country_id: "CS", country_icon: "" },
    { text: "Cuba", country_id: "CU", country_icon: "" },
    { text: "Cape Verde", country_id: "CV", country_icon: "" },
    { text: "Christmas Island", country_id: "CX", country_icon: "" },
    { text: "Cyprus", country_id: "CY", country_icon: "" },
    { text: "Czech Republic", country_id: "CZ", country_icon: "" },
    { text: "Germany", country_id: "DE", country_icon: "" },
    { text: "Djibouti", country_id: "DJ", country_icon: "" },
    { text: "Denmark", country_id: "DK", country_icon: "" },
    { text: "Dominica", country_id: "DM", country_icon: "" },
    { text: "Dominican Republic", country_id: "DO", country_icon: "" },
    { text: "Algeria", country_id: "DZ", country_icon: "" },
    { text: "Ecuador", country_id: "EC", country_icon: "" },
    { text: "Estonia", country_id: "EE", country_icon: "" },
    { text: "Egypt", country_id: "EG", country_icon: "" },
    { text: "Western Sahara", country_id: "EH", country_icon: "" },
    { text: "Eritrea", country_id: "ER", country_icon: "" },
    { text: "Spain", country_id: "ES", country_icon: "" },
    { text: "Ethiopia", country_id: "ET", country_icon: "" },
    { text: "Finland", country_id: "FI", country_icon: "" },
    { text: "Fiji", country_id: "FJ", country_icon: "" },
    { text: "Falkland Islands", country_id: "FK", country_icon: "" },
    { text: "Serbia", country_id: "RS", country_icon: "" },
    { text: "Micronesia", country_id: "FM", country_icon: "" },
    { text: "Faeroe Islands", country_id: "FO", country_icon: "" },
    { text: "France", country_id: "FR", country_icon: "" },
    { text: "Gabon", country_id: "GA", country_icon: "" },
    { text: "United Kingdom", country_id: "GB", country_icon: "" },
    { text: "Grenada", country_id: "GD", country_icon: "" },
    { text: "Georgia", country_id: "GE", country_icon: "" },
    { text: "French Guiana", country_id: "GF", country_icon: "" },
    { text: "Ghana", country_id: "GH", country_icon: "" },
    { text: "Gibraltar", country_id: "GI", country_icon: "" },
    { text: "Greenland", country_id: "GL", country_icon: "" },
    { text: "Gambia", country_id: "GM", country_icon: "" },
    { text: "Guinea", country_id: "GN", country_icon: "" },
    { text: "Guadaloupe", country_id: "GP", country_icon: "" },
    { text: "Equatorial Guinea", country_id: "GQ", country_icon: "" },
    { text: "Greece", country_id: "GR", country_icon: "" },
    { text: "South Georgia and the South Sandwich Islands", country_id: "GS", country_icon: "" },
    { text: "Guatemala", country_id: "GT", country_icon: "" },
    { text: "Guam", country_id: "GU", country_icon: "" },
    { text: "Guinea-Bissau", country_id: "GW", country_icon: "" },
    { text: "Guyana", country_id: "GY", country_icon: "" },
    { text: "Hong Kong", country_id: "HK", country_icon: "" },
    { text: "Heard and McDonald Islands", country_id: "HM", country_icon: "" },
    { text: "Honduras", country_id: "HN", country_icon: "" },
    { text: "Croatia", country_id: "HR", country_icon: "" },
    { text: "Haiti", country_id: "HT", country_icon: "" },
    { text: "Hungary", country_id: "HU", country_icon: "" },
    { text: "Indonesia", country_id: "ID", country_icon: "" },
    { text: "Ireland", country_id: "IE", country_icon: "" },
    { text: "Israel", country_id: "IL", country_icon: "" },
    { text: "India", country_id: "IN", country_icon: "" },
    { text: "British Indian Ocean Territory", country_id: "IO", country_icon: "" },
    { text: "Iraq", country_id: "IQ", country_icon: "" },
    { text: "Iran", country_id: "IR", country_icon: "" },
    { text: "Iceland", country_id: "IS", country_icon: "" },
    { text: "Italy", country_id: "IT", country_icon: "" },
    { text: "Jamaica", country_id: "JM", country_icon: "" },
    { text: "Jordan", country_id: "JO", country_icon: "" },
    { text: "Japan", country_id: "JP", country_icon: "" },
    { text: "Kenya", country_id: "KE", country_icon: "" },
    { text: "Kyrgyz Republic", country_id: "KG", country_icon: "" },
    { text: "Cambodia", country_id: "KH", country_icon: "" },
    { text: "Kiribati", country_id: "KI", country_icon: "" },
    { text: "Comoros", country_id: "KM", country_icon: "" },
    { text: "St. Kitts and Nevis", country_id: "KN", country_icon: "" },
    { text: "North Korea", country_id: "KP", country_icon: "" },
    { text: "Kuwait", country_id: "KW", country_icon: "" },
    { text: "Cayman Islands", country_id: "KY", country_icon: "" },
    { text: "Kazakhstan", country_id: "KZ", country_icon: "" },
    { text: "Lao People's Democratic Republic", country_id: "LA", country_icon: "" },
    { text: "Lebanon", country_id: "LB", country_icon: "" },
    { text: "St. Lucia", country_id: "LC", country_icon: "" },
    { text: "Liechtenstein", country_id: "LI", country_icon: "" },
    { text: "Sri Lanka", country_id: "LK", country_icon: "" },
    { text: "Liberia", country_id: "LR", country_icon: "" },
    { text: "Lesotho", country_id: "LS", country_icon: "" },
    { text: "Lithuania", country_id: "LT", country_icon: "" },
    { text: "Luxembourg", country_id: "LU", country_icon: "" },
    { text: "Latvia", country_id: "LV", country_icon: "" },
    { text: "Libyan Arab Jamahiriya", country_id: "LY", country_icon: "" },
    { text: "Morocco", country_id: "MA", country_icon: "" },
    { text: "Monaco", country_id: "MC", country_icon: "" },
    { text: "Moldova", country_id: "MD", country_icon: "" },
    { text: "Madagascar", country_id: "MG", country_icon: "" },
    { text: "Marshall Islands", country_id: "MH", country_icon: "" },
    { text: "Macedonia", country_id: "MK", country_icon: "" },
    { text: "Mali", country_id: "ML", country_icon: "" },
    { text: "Myanmar", country_id: "MM", country_icon: "" },
    { text: "Mongolia", country_id: "MN", country_icon: "" },
    { text: "Macao", country_id: "MO", country_icon: "" },
    { text: "Northern Mariana Islands", country_id: "MP", country_icon: "" },
    { text: "Martinique", country_id: "MQ", country_icon: "" },
    { text: "Mauritania", country_id: "MR", country_icon: "" },
    { text: "Montserrat", country_id: "MS", country_icon: "" },
    { text: "Malta", country_id: "MT", country_icon: "" },
    { text: "Mauritius", country_id: "MU", country_icon: "" },
    { text: "Maldives", country_id: "MV", country_icon: "" },
    { text: "Malawi", country_id: "MW", country_icon: "" },
    { text: "Mexico", country_id: "MX", country_icon: "" },
    { text: "Malaysia", country_id: "MY", country_icon: "" },
    { text: "Mozambique", country_id: "MZ", country_icon: "" },
    { text: "Namibia", country_id: "NA", country_icon: "" },
    { text: "New Caledonia", country_id: "NC", country_icon: "" },
    { text: "Niger", country_id: "NE", country_icon: "" },
    { text: "Norfolk Island", country_id: "NF", country_icon: "" },
    { text: "Nigeria", country_id: "NG", country_icon: "" },
    { text: "Montenegro", country_id: "ME", country_icon: "" },
    { text: "Nicaragua", country_id: "NI", country_icon: "" },
    { text: "Netherlands", country_id: "NL", country_icon: "" },
    { text: "Norway", country_id: "NO", country_icon: "" },
    { text: "Nepal", country_id: "NP", country_icon: "" },
    { text: "Nauru", country_id: "NR", country_icon: "" },
    { text: "Niue", country_id: "NU", country_icon: "" },
    { text: "New Zealand", country_id: "NZ", country_icon: "" },
    { text: "Oman", country_id: "OM", country_icon: "" },
    { text: "Panama", country_id: "PA", country_icon: "" },
    { text: "Peru", country_id: "PE", country_icon: "" },
    { text: "French Polynesia", country_id: "PF", country_icon: "" },
    { text: "Papua New Guinea", country_id: "PG", country_icon: "" },
    { text: "Philippines", country_id: "PH", country_icon: "" },
    { text: "Yugoslavia", country_id: "YU", country_icon: "" },
    { text: "Kosovo", country_id: "XK", country_icon: "" },
    { text: "Czechoslovakia", country_id: "XC", country_icon: "" },
    { text: "Pakistan", country_id: "PK", country_icon: "" },
    { text: "Poland", country_id: "PL", country_icon: "" },
    { text: "St. Pierre and Miquelon", country_id: "PM", country_icon: "" },
    { text: "Pitcairn Island", country_id: "PN", country_icon: "" },
    { text: "Puerto Rico", country_id: "PR", country_icon: "" },
    { text: "Palestinian Territory", country_id: "PS", country_icon: "" },
    { text: "Portugal", country_id: "PT", country_icon: "" },
    { text: "Palau", country_id: "PW", country_icon: "" },
    { text: "Paraguay", country_id: "PY", country_icon: "" },
    { text: "Qatar", country_id: "QA", country_icon: "" },
    { text: "Reunion", country_id: "RE", country_icon: "" },
    { text: "Romania", country_id: "RO", country_icon: "" },
    { text: "Russia", country_id: "RU", country_icon: "" },
    { text: "Rwanda", country_id: "RW", country_icon: "" },
    { text: "Saudi Arabia", country_id: "SA", country_icon: "" },
    { text: "Solomon Islands", country_id: "SB", country_icon: "" },
    { text: "Seychelles", country_id: "SC", country_icon: "" },
    { text: "Sudan", country_id: "SD", country_icon: "" },
    { text: "Sweden", country_id: "SE", country_icon: "" },
    { text: "Singapore", country_id: "SG", country_icon: "" },
    { text: "St. Helena", country_id: "SH", country_icon: "" },
    { text: "Slovenia", country_id: "SI", country_icon: "" },
    { text: "Svalbard & Jan Mayen Islands", country_id: "SJ", country_icon: "" },
    { text: "Slovakia", country_id: "SK", country_icon: "" },
    { text: "Sierra Leone", country_id: "SL", country_icon: "" },
    { text: "San Marino", country_id: "SM", country_icon: "" },
    { text: "Senegal", country_id: "SN", country_icon: "" },
    { text: "Somalia", country_id: "SO", country_icon: "" },
    { text: "Suriname", country_id: "SR", country_icon: "" },
    { text: "Sao Tome and Principe", country_id: "ST", country_icon: "" },
    { text: "El Salvador", country_id: "SV", country_icon: "" },
    { text: "Syrian Arab Republic", country_id: "SY", country_icon: "" },
    { text: "Swaziland", country_id: "SZ", country_icon: "" },
    { text: "Turks and Caicos Islands", country_id: "TC", country_icon: "" },
    { text: "Chad", country_id: "TD", country_icon: "" },
    { text: "French Southern Territories", country_id: "TF", country_icon: "" },
    { text: "Togo", country_id: "TG", country_icon: "" },
    { text: "Thailand", country_id: "TH", country_icon: "" },
    { text: "Tajikistan", country_id: "TJ", country_icon: "" },
    { text: "Tokelau", country_id: "TK", country_icon: "" },
    { text: "Timor-Leste", country_id: "TL", country_icon: "" },
    { text: "Turkmenistan", country_id: "TM", country_icon: "" },
    { text: "Tunisia", country_id: "TN", country_icon: "" },
    { text: "Tonga", country_id: "TO", country_icon: "" },
    { text: "Turkey", country_id: "TR", country_icon: "" },
    { text: "Trinidad and Tobago", country_id: "TT", country_icon: "" },
    { text: "Tuvalu", country_id: "TV", country_icon: "" },
    { text: "Taiwan", country_id: "TW", country_icon: "" },
    { text: "Tanzania", country_id: "TZ", country_icon: "" },
    { text: "Ukraine", country_id: "UA", country_icon: "" },
    { text: "Uganda", country_id: "UG", country_icon: "" },
    { text: "United States Minor Outlying Islands", country_id: "UM", country_icon: "" },
    { text: "United States of America", country_id: "US", country_icon: "" },
    { text: "Uruguay", country_id: "UY", country_icon: "" },
    { text: "Uzbekistan", country_id: "UZ", country_icon: "" },
    { text: "Holy See", country_id: "VA", country_icon: "" },
    { text: "St. Vincent and the Grenadines", country_id: "VC", country_icon: "" },
    { text: "Venezuela", country_id: "VE", country_icon: "" },
    { text: "British Virgin Islands", country_id: "VG", country_icon: "" },
    { text: "US Virgin Islands", country_id: "VI", country_icon: "" },
    { text: "Vietnam", country_id: "VN", country_icon: "" },
    { text: "Vanuatu", country_id: "VU", country_icon: "" },
    { text: "Wallis and Futuna Islands", country_id: "WF", country_icon: "" },
    { text: "Samoa", country_id: "WS", country_icon: "" },
    { text: "Yemen", country_id: "YE", country_icon: "" },
    { text: "Mayotte", country_id: "YT", country_icon: "" },
    { text: "South Africa", country_id: "ZA", country_icon: "" },
    { text: "Zambia", country_id: "ZM", country_icon: "" },
    { text: "Zimbabwe", country_id: "ZW", country_icon: "" },
    { text: "South Korea", country_id: "KR", country_icon: "" },
    { text: "East Germany", country_id: "XG", country_icon: "" },
    { text: "Soviet Union", country_id: "SU", country_icon: "" },
    { text: "South Sudan", country_id: "SS", country_icon: "" }
  ]
}